import Head from 'next/head';

const Header = () => {
    return (
        <div>
            <Head>
                <title>My Three.js with Next.js App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                {/* <link rel="stylesheet" href="styles.css" /> */}
                {/* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" /> */}
            </Head>
        </div>
    );
}

export default Header;